automation:
  - alias: "Christmas Decorations on at Dusk"
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:45:00"
    action:
      - service: switch.turn_on
        target:
          entity_id: group.decoration_lights

  - alias: "Christmas Decorations off at night"
    trigger:
      - platform: time
        at: "00:30"
    action:
      - service: switch.turn_off
        target:
          entity_id: group.decoration_lights

group:
  decoration_lights:
    name: Christmas Lights
    icon: "mdi:pine-tree"
    entities:
      - light.smartdimmer1
      - switch.smartplug1
      - switch.smartplug2

