automation:
  - alias: "Christmas Decorations on at Dusk"
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:45:00"
    action:
      - service: scene.apply
        data:
          entities:
            group.decoration_lights: on

  - alias: "Christmas Decorations off at night"
    trigger:
      - platform: time
        at: "00:30"
    action:
      - service: scene.apply
        data:
          entities: 
            group.decoration_lights: off

group:
  decoration_lights:
    name: Christmas Lights
    icon: "mdi:pine-tree"
    entities:
      - light.smartdimmer1
      - switch.smartplug1
      - switch.smartplug2

