  input_boolean:
    cleaner_access:
      name: Enable the cleaner door code

    autolock:
      name: Automatically relock the doors

  script:
    add_cleaner_code:
      alias: 'Lock: Add cleaner code'
      mode: single
      sequence:
        - service: zwave_js.set_lock_usercode
          data:
            entity_id:
              - lock.basement
              - lock.frontdoor
            code_slot: 3
            usercode: !secret cleaner_door_code
        - service: input_boolean.turn_on
          entity_id: input_boolean.cleaner_access


    remove_cleaner_code:
      alias: 'Lock: Remove cleaner code'
      mode: single
      sequence:
        - service: zwave_js.clear_lock_usercode
          data:
            entity_id:
              - lock.basement
              - lock.frontdoor
            code_slot: 3
        - service: input_boolean.turn_off
          entity_id: input_boolean.cleaner_access


  automation:
    - alias: Enable Cleaner Access
      trigger:
        platform: state
        entity_id: input_boolean.cleaner_access
        from: 'off'
        to: 'on'
      action:
        service: script.turn_on
        entity_id: script.add_cleaner_code

    - alias: Disable Cleaner Access
      trigger:
        platform: state
        entity_id: input_boolean.cleaner_access
        from: 'on'
        to: 'off'
      action:
        service: script.turn_on
        entity_id: script.remove_cleaner_code

    - alias: Automatic Lock front door
      trigger:
        platform: state
        entity_id: lock.frontdoor
        from: 'locked'
        to: 'unlocked'
        for: '00:15:00'
      condition:
        alias: "Autolock is enabled and the door is still unlocked"
        condition: and
        conditions:
          - condition: state
            entity_id: lock.frontdoor
            state: 'unlocked'
          - condition: state
            entity_id: input_boolean.autolock
            state: 'on'
      action: 
        service: lock.lock
        entity_id: lock.frontdoor

