---
version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable

    volumes:
      - "./homeassistant:/config"

    environment:
      - TZ=America/New_York

    restart: unless-stopped
    network_mode: host

  zwavejs:
    container_name: zwavejs
    image: zwavejs/zwavejs2mqtt:2.4.1
    tty: true
    stop_signal: SIGINT
    restart: unless-stopped
    devices:
      - "/dev/serial/by-id/usb-0658_0200_01FFFFFF-FFFF-FFFF-FFFF-150916075924-if00:/dev/ttyACM0:rmw"  # homeseer
      # - "/dev/serial/by-id/usb-0658_0200-if00:/dev/ttyACM0:rmw"  # aeotech
    volumes:
      - "./zwavejs2mqtt:/usr/src/app/store"
    network_mode: host
