---
version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable

    volumes:
      - "./homeassistant:/config"

    environment:
      - TZ=America/New_York

    restart: unless-stopped
    network_mode: host
