- id: '1611759104735'
  alias: Laundry Lighting
  description: turns on utility room lights
  use_blueprint:
    path: homeassistant/motion_switch.yaml
    input:
      no_motion_wait: 600
      motion_entity: binary_sensor.utilitysensor_home_security_motion_detection
      switch_target:
        device_id: fc78bfbecfaee49aa29b3c42c04959b6
- id: '1613319585064'
  alias: Control Floodlight from deck
  description: ''
  use_blueprint:
    path: homeassistant/multitap.yaml
    input:
      homeseer_switch: b1532caedaebc441963f5fe0b28bb8e1
      button_a2:
      - type: turn_on
        device_id: 0d1390a64d8306c2cc53d12a9dcf1915
        entity_id: light.floodlight
        domain: light
      button_b2:
      - type: turn_off
        device_id: 0d1390a64d8306c2cc53d12a9dcf1915
        entity_id: light.floodlight
        domain: light
      button_a3: []
      button_a_held: []
      button_b_held: []
- id: '1613332049244'
  alias: Trigger cleaning day
  description: Enable cleaner's access
  trigger:
  - platform: time
    at: '8:00'
  condition:
  - condition: time
    weekday:
    - fri
  action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.cleaner_access
  - delay: 08:00
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.cleaner_access
  mode: single
- id: '1613333588711'
  alias: Office lamp
  description: Turn on the office lamp when I'm in the room, and the lights are low
  trigger:
  - platform: state
    to: 'on'
    entity_id: binary_sensor.officesensor_home_security_motion_detection
  condition:
  - condition: numeric_state
    entity_id: sensor.officesensor_illuminance
    below: '23'
  action:
  - type: turn_on
    device_id: 819414552a1e5219fa6d112660fba929
    entity_id: switch.smart_switch_6
    domain: switch
  - wait_for_trigger:
    - platform: state
      from: 'on'
      to: 'off'
      entity_id: binary_sensor.officesensor_home_security_motion_detection
  - wait_template: ''
    timeout: '60'
  - type: turn_off
    device_id: 819414552a1e5219fa6d112660fba929
    entity_id: switch.smart_switch_6
    domain: switch
  mode: restart
  max_exceeded: silent
- id: '1613414120164'
  alias: Lock all the doors when I leave home
  description: ''
  trigger:
  - platform: zone
    entity_id: person.chris_flipse
    zone: zone.home
    event: leave
  action:
  - service: script.lock_all_doors
    data: {}
  mode: restart
- id: '1615922538846'
  alias: Turn on great room light at dusk
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -0:30:00
  condition:
  - condition: device
    device_id: ee1b7c9f184248b59ee5e6923a6f4e3e
    domain: media_player
    entity_id: media_player.great_room_tv
    type: is_off
  action:
  - type: turn_on
    device_id: 589d5e63125d799f782acc855c9a8fcd
    entity_id: light.readinglight
    domain: light
    brightness_pct: 90
  mode: single
- id: '1615923510099'
  alias: lockdown at night
  description: ''
  trigger:
  - platform: time
    at: '22:00'
  condition: []
  action:
  - service: script.lock_all_doors
    data: {}
  - device_id: 09c6fe0c339f9ebddc4a06c2a0ae45d2
    domain: cover
    entity_id: cover.left_side
    type: close
  - device_id: fb4fde03fffae59d2681592eb9b82a89
    domain: cover
    entity_id: cover.right_side
    type: close
  mode: single
- id: '1615941665066'
  alias: tv time
  description: ''
  trigger:
  - platform: device
    device_id: ee1b7c9f184248b59ee5e6923a6f4e3e
    domain: media_player
    entity_id: media_player.great_room_tv
    type: playing
  condition: []
  action:
  - type: turn_off
    device_id: 589d5e63125d799f782acc855c9a8fcd
    entity_id: light.readinglight
    domain: light
  mode: single
- id: '1617723450648'
  alias: Turn on Towel Rack in the morning
  description: ''
  trigger:
  - platform: time
    at: '6:00'
  condition: []
  action:
  - type: turn_on
    device_id: 7f9e4e0cc37d22565b24839e2d96dd2b
    entity_id: switch.towelrack
    domain: switch
  mode: single
- id: '1619096261881'
  alias: Turn off towel rack
  description: ''
  use_blueprint:
    path: homeassistant/multitap.yaml
    input:
      button_b2:
      - type: turn_off
        device_id: 7f9e4e0cc37d22565b24839e2d96dd2b
        entity_id: switch.towelrack
        domain: switch
      homeseer_switch: 1d0de3dc70e8749f63d93124929ca77e
      button_a2:
      - type: turn_on
        device_id: 7f9e4e0cc37d22565b24839e2d96dd2b
        entity_id: switch.towelrack
        domain: switch
