lock_all_doors:
  alias: Lock all doors
  sequence:
  - device_id: c24e4f96f88827cce63ff0891a8ee0fb
    domain: lock
    entity_id: lock.basement
    type: lock
  - device_id: 5d7e6ff4cc316a1adf9bd1f0632640aa
    domain: lock
    entity_id: lock.frontdoor
    type: lock
  mode: single
  icon: mdi:lock
