- id: '1611759104735'
  alias: Laundry Lighting
  description: turns on utility room lights
  use_blueprint:
    path: homeassistant/motion_switch.yaml
    input:
      no_motion_wait: '600'
      motion_entity: binary_sensor.utility_room_sensor_home_security_motion_detection_2
      switch_target:
        entity_id:
        - switch.utility_lights_current_value_2
- id: '1613319585064'
  alias: Control Floodlight from deck
  description: ''
  use_blueprint:
    path: homeassistant/multitap.yaml
    input:
      homeseer_switch: 45f791a29a1696accabe141150fa24fb
      button_a2:
      - service: light.turn_on
        data: {}
        entity_id: light.flood_light_current_value
      button_b2:
      - type: turn_off
        device_id: 20c203fecca7c2d594f59b29c14a9be9
        entity_id: light.flood_light_current_value
        domain: light
      button_a3: []
      button_a_held: []
      button_b_held: []
- id: '1613332049244'
  alias: Trigger cleaning day
  description: Enable cleaner's access
  trigger:
  - platform: time
    at: '8:00'
  condition:
  - condition: time
    weekday:
    - fri
  action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.cleaner_access
  - delay: 08:00
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.cleaner_access
  mode: single
- id: '1613333588711'
  alias: Office lamp
  description: Turn on the office lamp when I'm in the room, and the lights are low
  trigger:
  - platform: state
    entity_id: binary_sensor.office_home_security_motion_detection
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.office_illuminance
    below: '23'
  action:
  - type: turn_on
    device_id: 6224466d47425a536ec34a34f7842ee5
    entity_id: light.plugin_dimmer_current_value
    domain: light
    brightness_pct: 100
  - wait_for_trigger:
    - platform: state
      entity_id: binary_sensor.office_home_security_motion_detection
      from: 'on'
      to: 'off'
  - wait_template: ''
    timeout: '60'
  - type: turn_off
    device_id: 6224466d47425a536ec34a34f7842ee5
    entity_id: light.plugin_dimmer_current_value
    domain: light
  mode: restart
  max_exceeded: silent
