- alias: Enable Cleaner Access
  trigger:
    platform: state
    entity_id: input_boolean.cleaner_access
    from: 'off'
    to: 'on'
  action:
    service: script.turn_on
    entity_id: script.add_cleaner_code
