---
version: "3"
services:
  zwavejs:
    container_name: zwavejs
    image: zwavejs/zwavejs2mqtt:3.3.0

    tty: true

    stop_signal: SIGINT
    restart: unless-stopped
    devices:
      #- "/dev/serial/by-id/usb-0658_0200_01FFFFFF-FFFF-FFFF-FFFF-150916075924-if00:/dev/ttyACM0:rmw"  # homeseer
      - "/dev/serial/by-id/usb-0658_0200-if00:/dev/ttyACM0:rmw"  # aeotech
    volumes:
      - "./store:/usr/src/app/store"
    ports:
      - "8091:8091"
      - "8095:8095"
